# Generated by Django 4.2.11 on 2024-03-14 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('paused', 'En pause'), ('planned', 'Planifié'), ('pending', 'En cours'), ('delivered', 'Livré')], max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=20)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_tasks', to='project_app.user')),
                ('progress_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='project_app.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_managed', to='project_app.user'),
        ),
    ]
