# Generated by Django 5.0.1 on 2024-04-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depend_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depend_tasks', to='project_app.task'),
        ),
    ]
