# Generated by Django 4.2.11 on 2024-03-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='project_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('paused', 'En pause'), ('planned', 'Planifié'), ('ongoing', 'En cours'), ('completed', 'Réalisée'), ('validated', 'Validée')], max_length=20),
        ),
    ]
