# Generated by Django 5.0.1 on 2024-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_task_depend_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='depend_task',
        ),
        migrations.AddField(
            model_name='task',
            name='depend_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='project_app.task'),
        ),
    ]
