# Generated by Django 5.0.3 on 2024-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('paused', 'En pause'), ('planned', 'Planifié'), ('pending', 'En cours'), ('delivered', 'Livré')], default='planned', max_length=20),
        ),
    ]
