# Generated by Django 5.0.1 on 2024-04-05 19:25

from django.db import migrations
from authentification.group import create_groups

class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
